project:
  type: website

website:
  title: "Aulas_finance"
  navbar:
    left:
      - href: Finance_R_1.qmd
        text: Home
       

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

